<h1>
<center>
Final Project: Part 3 Tuning: Wine Quality
</center>
</h1>

# Random Forest

In the last notebook I created a decision tree and tested it with K Folding as well as building a random forest and testing the accuracy of the models. I found that K folding was more successful at modeling this data so for part 3 I am going to tune the random forest to model the data better.

# Read in spreadsheet

In [19]:
import pandas as pd
import os

url = 'https://docs.google.com/spreadsheets/d/1SF9DGShsQOv0IyxjMIHzQUZbjFwXzY3eC8SSofl53xI/export?format=csv'
wine_table = pd.read_csv(url)

In [20]:
#I am setting the option to see all the columns of our table as we build it.
pd.set_option('display.max_columns', None)

In [21]:
# Check to make sure wine_table is looking correct
wine_table.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [22]:
home_path =  os.path.expanduser('~')
os.chdir(home_path + '/CIS_399/datascience_1/')
!git pull

Already up-to-date.

In [23]:
import sys
sys.path.append(home_path + '/CIS_399/datascience_1')
from week7 import *
%who function

accuracy	 assign_nulls	 batch_ohe	 build_pred	 build_tree_iter	 caser	 closest_centroid	 compute_mean	 compute_prediction
compute_training	 euclidean_distance	 f1	 find_best_splitter	 forest_builder	 generate_table	 gig	 gini	 informedness
initialize_centroids	 k_fold	 k_means	 phase_1	 phase_2	 predictor_case	 probabilities	 row_to_vect	 seeder
tree_predictor	 vote_taker	 wine_quality_split

I am going to look at the quality values and create my cutoff point for high and low quality wines. This way we have a binary target column (high quality wines) that we can look for.

In [24]:
# I'm going to write a function specifically for splitting the wine quality because values of 6 are very high
# and I want to see if changing high quality wines to include/exclude ratings of 6 have any influence on predictions
def wine_quality_split(table, cutoff):
    # cutoff is included in low quality
    table['h_quality'] = table.apply(lambda row: 1 if row.quality > cutoff else 0, axis=1)
    table['l_quality'] = table.apply(lambda row: 0 if row.h_quality == 1 else 1, axis=1)
    return table

In [25]:
# going to set the cutoff at 6 so the high quality counts should only include 7 and 8
wine_table = wine_quality_split(wine_table, 5)

# the value counts should be opposite
print(wine_table['h_quality'].value_counts())
print()
print(wine_table['l_quality'].value_counts())

1    855
0    744
Name: h_quality, dtype: int64

0    855
1    744
Name: l_quality, dtype: int64

In [26]:
# none of these columns are binary so I am going to OHE some of them for predictors
# I am going to use chlorides, total sulfur dioxide, residual sugar, density, and quality

ohe_columns = [
    'chlorides',
    'total sulfur dioxide',
    'residual sugar',
    'density',
    'quality'
]

In [27]:
def batch_ohe(table, targets, bins):
    """ writing this function to One Hot Encode multiple non-binary columns in one function call"""
    for target in targets:
        print("Binning " + target)
        bin_names = []
        bin_names.append('Low')
        bin_names.append('Medium')
        bin_names.append('High')
        
        bin_name = target.replace(' ', '') + '_bin'
        
        table[bin_name] = pd.cut(table[target], bins, labels=bin_names)
        print(table[bin_name].value_counts())
        print("One Hot Encoding " + target)
        
        target = target.replace(' ', '')
        one_hot_e = pd.get_dummies(table[bin_name],prefix=target,dummy_na=False)  # false because should not have empties
        table = table.join(one_hot_e)
        
        print()
        
        table = table.drop(bin_name, axis=1)
    return table

In [28]:
splitter_columns = [
    'chlorides_Low',
    'chlorides_Medium',
    'chlorides_High',
    'residualsugar_Low',
    'residualsugar_Medium',
    'residualsugar_High',
    'density_Low',
    'density_Medium',
    'density_High',
    'quality_Low',
    'quality_Medium',
    'quality_High'
]

In [29]:
#pulled from my K_Means notebook.

def assign_nulls(table, target):
    """
    table => our input table (wine_table in this case)
    target => our target column
    """
    #length of column
    column_size = len(table[target])
    
    #using a ratio of 10 to 30 percent nulls, may add customization to this later
    ratio = float(random.randint(10, 30)/100)
    int_ratio = int(ratio * column_size)
    
    #gather random indices
    indices = random.sample(range(column_size), int_ratio)
    #sourced from https://stackoverflow.com/questions/6482889/get-random-sample-from-list-while-maintaining-ordering-of-items
    
    #assign nulls to randomly selected indices
    for i in indices:
        table.at[i, target] = float("NaN")
    
    return table

In [30]:
#assign random nulls to all my ohe columns
wine_table['quality'] = wine_table.apply(lambda row: float(row.quality), axis=1)
for target in ohe_columns:
    wine_table=assign_nulls(wine_table, target)

In [31]:
wine_table = batch_ohe(wine_table, ohe_columns, 3)

Binning chlorides
Low       1144
Medium      15
High         9
Name: chlorides_bin, dtype: int64
One Hot Encoding chlorides

Binning total sulfur dioxide
Low       1178
Medium     100
High         2
Name: totalsulfurdioxide_bin, dtype: int64
One Hot Encoding total sulfur dioxide

Binning residual sugar
Low       1297
Medium      40
High         7
Name: residualsugar_bin, dtype: int64
One Hot Encoding residual sugar

Binning density
Medium    970
Low       129
High      117
Name: density_bin, dtype: int64
One Hot Encoding density

Binning quality
Medium    954
High      167
Low        47
Name: quality_bin, dtype: int64
One Hot Encoding quality

In [32]:
wine_table.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,h_quality,l_quality,chlorides_Low,chlorides_Medium,chlorides_High,totalsulfurdioxide_Low,totalsulfurdioxide_Medium,totalsulfurdioxide_High,residualsugar_Low,residualsugar_Medium,residualsugar_High,density_Low,density_Medium,density_High,quality_Low,quality_Medium,quality_High
0,7.4,0.70,0.00,1.9,0.076,11.0,NaN,0.9978,3.51,0.56,9.4,5.0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,NaN,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0
3,11.2,0.28,0.56,NaN,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0

# Random Forest (5 times)

Since the random forest is in fact random I am going to run a few tests at the same amount of trees and see how our accuracy changes. In my part 2 notebook my random forest was not performing very well but in this notebook with new random NaN data, my random forest was improving.

(I call them all forest2 so it doesn't take up too much space in the wine_table)

In [33]:
forest2 = forest_builder(wine_table, splitter_columns, 'h_quality', hypers={'total-trees': 15})
len(forest2)

wine_table['forest_2'] = wine_table.apply(lambda row: vote_taker(row, forest2), axis=1)

wine_table['forest_2_type'] = wine_table.apply(lambda row: predictor_case(row, pred='forest_2', target='h_quality'), axis=1)

forest2_types = wine_table['forest_2_type'].value_counts()  # returns a series
print(forest2_types)
print((accuracy(forest2_types), f1(forest2_types), informedness(forest2_types)))

true_positive     582
true_negative     381
false_positive    363
false_negative    273
Name: forest_2_type, dtype: int64
(0.6022514071294559, 0.6466666666666667, 0.1927985285795133)

In [34]:
forest2 = forest_builder(wine_table, splitter_columns, 'h_quality', hypers={'total-trees': 15})
len(forest2)

wine_table['forest_2'] = wine_table.apply(lambda row: vote_taker(row, forest2), axis=1)

wine_table['forest_2_type'] = wine_table.apply(lambda row: predictor_case(row, pred='forest_2', target='h_quality'), axis=1)

forest2_types = wine_table['forest_2_type'].value_counts()  # returns a series
print(forest2_types)
print((accuracy(forest2_types), f1(forest2_types), informedness(forest2_types)))

true_positive     563
false_positive    378
true_negative     366
false_negative    292
Name: forest_2_type, dtype: int64
(0.5809881175734835, 0.6269487750556793, 0.1504150160347104)

In [35]:
forest2 = forest_builder(wine_table, splitter_columns, 'h_quality', hypers={'total-trees': 15})
len(forest2)

wine_table['forest_2'] = wine_table.apply(lambda row: vote_taker(row, forest2), axis=1)

wine_table['forest_2_type'] = wine_table.apply(lambda row: predictor_case(row, pred='forest_2', target='h_quality'), axis=1)

forest2_types = wine_table['forest_2_type'].value_counts()  # returns a series
print(forest2_types)
print((accuracy(forest2_types), f1(forest2_types), informedness(forest2_types)))

true_negative     533
true_positive     436
false_negative    419
false_positive    211
Name: forest_2_type, dtype: int64
(0.6060037523452158, 0.5805592543275633, 0.22633936993020187)

In [42]:
forest2 = forest_builder(wine_table, splitter_columns, 'h_quality', hypers={'total-trees': 15})
len(forest2)

wine_table['forest_2'] = wine_table.apply(lambda row: vote_taker(row, forest2), axis=1)

wine_table['forest_2_type'] = wine_table.apply(lambda row: predictor_case(row, pred='forest_2', target='h_quality'), axis=1)

forest2_types = wine_table['forest_2_type'].value_counts()  # returns a series
print(forest2_types)
print((accuracy(forest2_types), f1(forest2_types), informedness(forest2_types)))

true_negative     569
false_negative    445
true_positive     410
false_positive    175
Name: forest_2_type, dtype: int64
(0.6122576610381488, 0.5694444444444444, 0.24431710997924916)

# Results

It looks like with this specific set of data and the random forest having 15 trees (which was the optimal amount in the last notebook) the accuracy of this forest generally sits around 60%. Lets see if we can improve that.

This accuracy has a lot to do with the cutoff of the wine quality. As I will show in the next cell, when the cutoff is changed to 6 (meaning that low quality includes ratings of 1-6, and high quality 7-10) the random forest's accuracy jumps to 89-90%. This is due to the amount of high quality wines being closer to outliers and more distinguishable than their counterparts. 

My guess is that the random forest is struggling with the identifications of wines that are rated 5 and wines that are rated 6. This is because they most likely have similar classification values. We can see this because there is a super high amount of false_negative and false_positive values. I believe that if we can decrease these numbers than the accuracy will increase. The forest needs to be built to look for specifically differences between 5 and 6.

In [38]:
# example of higher cutoff

# read in new table
example_wine_table = pd.read_csv(url)
pd.set_option('display.max_columns', None)

# split quality at 6
example_wine_table = wine_quality_split(example_wine_table, 6)

# assign random nulls to all my ohe columns
example_wine_table['quality'] = example_wine_table.apply(lambda row: float(row.quality), axis=1)
for target in ohe_columns:
    example_wine_table=assign_nulls(example_wine_table, target)

# one hot encode all columns
example_wine_table = batch_ohe(example_wine_table, ohe_columns, 3)

# creating example forest
example_forest = forest_builder(example_wine_table, splitter_columns, 'h_quality', hypers={'total-trees': 15})
len(example_forest)

example_wine_table['example_forest'] = example_wine_table.apply(lambda row: vote_taker(row, example_forest), axis=1)

example_wine_table['example_forest_type'] = example_wine_table.apply(lambda row: predictor_case(row, pred='example_forest', target='h_quality'), axis=1)

example_forest_types = example_wine_table['example_forest_type'].value_counts()  # returns a series
print(example_forest_types)
print((accuracy(example_forest_types), f1(example_forest_types), informedness(example_forest_types)))

Binning chlorides
Low       1157
Medium      18
High         9
Name: chlorides_bin, dtype: int64
One Hot Encoding chlorides

Binning total sulfur dioxide
Low       1121
Medium      94
High         1
Name: totalsulfurdioxide_bin, dtype: int64
One Hot Encoding total sulfur dioxide

Binning residual sugar
Low       1309
Medium      42
High         9
Name: residualsugar_bin, dtype: int64
One Hot Encoding residual sugar

Binning density
Medium    1018
Low        135
High       127
Name: density_bin, dtype: int64
One Hot Encoding density

Binning quality
Medium    1109
High       184
Low         51
Name: quality_bin, dtype: int64
One Hot Encoding quality

true_negative     1382
false_negative     129
true_positive       88
Name: example_forest_type, dtype: int64
(0.9193245778611632, 0.5770491803278689, 0.4055299539170507)

As you can see the accuracy was upwards of 97% (The first time I ran it). This cutoff is very important to the accuracy of this data. I am going to try to improve the accuracy when the cutoff is 5.

# Improving Accuracy

I'm going to start by creating a sample table that just includes wines with ratings of 5 and 6 and do some analysis on those. These will tell me when the predictions are failing. Perhaps a certain column is throwing off the predictions. I have a feeling I am going to be altering the vote taker.

In [45]:
wine_table_5 = wine_table.loc[wine_table['quality'] == 5.0]
wine_table_5.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,h_quality,l_quality,chlorides_Low,chlorides_Medium,chlorides_High,totalsulfurdioxide_Low,totalsulfurdioxide_Medium,totalsulfurdioxide_High,residualsugar_Low,residualsugar_Medium,residualsugar_High,density_Low,density_Medium,density_High,quality_Low,quality_Medium,quality_High,forest_2,forest_2_type
0,7.4,0.700,0.00,1.9,0.076,11.0,NaN,0.9978,3.51,0.56,9.4,5.0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,true_negative
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,true_negative
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,true_negative
5,7.4,0.660,0.00,1.8,0.075,13.0,NaN,0.9978,3.51,0.56,9.4,5.0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,true_negative
11,7.5,0.500,0.36,6.1,NaN,17.0,102.0,0.9978,3.35,0.80,10.5,5.0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,true_negative
12,5.6,0.615,0.00,1.6,0.089,16.0,NaN,0.9943,3.58,0.52,9.9,5.0,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,false_positive
14,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2,5.0,0,1,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,true_negative
15,8.9,0.620,0.19,3.9,0.170,51.0,NaN,NaN,3.17,0.93,9.2,5.0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,true_negative
21,7.6,0.390,0.31,2.3,0.082,23.0,71.0,0.9982,3.52,0.65,9.7,5.0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,true_negative
22,7.9,0.430,0.21,1.6,0.106,10.0,NaN,0.9966,3.17,0.91,9.5,5.0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,true_negative

In [46]:
wine_table_6 = wine_table.loc[wine_table['quality'] == 6.0]
wine_table_6.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,h_quality,l_quality,chlorides_Low,chlorides_Medium,chlorides_High,totalsulfurdioxide_Low,totalsulfurdioxide_Medium,totalsulfurdioxide_High,residualsugar_Low,residualsugar_Medium,residualsugar_High,density_Low,density_Medium,density_High,quality_Low,quality_Medium,quality_High,forest_2,forest_2_type
3,11.2,0.280,0.56,NaN,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,false_negative
24,6.9,0.400,0.14,2.4,0.085,21.0,40.0,0.9968,3.43,0.63,9.7,6.0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative
31,6.9,0.685,0.00,2.5,0.105,22.0,37.0,0.9966,3.46,0.57,10.6,6.0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative
33,6.9,0.605,0.12,NaN,0.073,40.0,83.0,0.9993,3.45,0.52,9.4,6.0,1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,false_negative
35,7.8,0.645,0.00,5.5,0.086,5.0,NaN,NaN,3.40,0.55,9.6,6.0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,false_negative
36,7.8,0.600,0.14,2.4,0.086,3.0,15.0,0.9975,3.42,0.60,10.8,6.0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative
42,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.9968,3.21,0.90,10.5,6.0,1,0,0,1,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative
51,6.6,0.520,0.04,2.2,0.069,8.0,15.0,0.9956,3.40,0.63,9.4,6.0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative
52,6.6,0.500,0.04,2.1,NaN,6.0,14.0,NaN,3.39,0.64,9.4,6.0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,false_negative
54,7.6,0.510,0.15,2.8,NaN,33.0,73.0,0.9955,3.17,0.63,10.2,6.0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,false_negative

Interesting... in the first ten rows of wine_table_5 and wine_table_6 all of the 5's are true_negative and all of the 6's are false_negative. Are they always rated this way?

In [47]:
print("Wine Table 5:")
print(wine_table_5['forest_2_type'].value_counts())
print()
print("Wine Table 6:")
print(wine_table_6['forest_2_type'].value_counts())

Wine Table 5:
true_negative     476
false_positive     19
Name: forest_2_type, dtype: int64

Wine Table 6:
false_negative    413
true_positive      46
Name: forest_2_type, dtype: int64

This is looking like most of the wines that have a quality of 5 are being classified correctly, but most of the wines with a quality of 6 are being classified as low quality. Our issue is predicting a wine quality of 6. Lets build a matrix of tree predictions for each table so we can really see how similar these classifications are.

# Matrix of Votes

I am going to figure out how to tune the random forest by using a matrix of votes from the previous random forest. Since I have two sub-tables (one for 5's and one for 6's) I can create an individual matrix of votes for each subtable based on the previous random forest and gather how each classification would be voted.

Once I have both matrices I will find all of the matches between them which will give me some really useful information. Since the 6's are generally incorrectly classified I'm hoping there will be a clear sequence of votes that regularily occurs in the correct ones and then I can use this to help classify the other incorrect ones.

In [153]:
def compute_matrix(forest, table):
    matrix = []
    
    # I'm going to redefine vote_taker for the scope of this function because I need a row of predictions
    # not a single vote and I don't want this change made global
    
    def vote_taker(row, forest):
        votes = []
        for tree in forest:
            prediction = tree_predictor(row, tree)
            votes.append(prediction)  #ties go to 0
        return votes

    for index, row in table.iterrows():
        votes = vote_taker(row, forest)
        matrix.append(votes)
        
    #print(len(matrix))
    return matrix

In [155]:
matrix_5 = compute_matrix(forest2, wine_table_5)
matrix_6 = compute_matrix(forest2, wine_table_6)

In [188]:
print("Length matrix_5:")
print(len(matrix_5))
print()
print("Length matrix_6:")
print(len(matrix_6))

# lets see how many of these predictions match each other

def match_predictions(matrix1, matrix2):
    matches1 = {}
    nonmatches1 = {}
    for i in range(len(matrix1)):
        row = matrix1[i]
        if row in matrix2:
            key = ''.join(str(e) for e in row)
            if key in matches1:
                matches1[key] += 1
            else:
                matches1[key] = 1
        else:
            key = ''.join(str(e) for e in row)
            if key in nonmatches1:
                nonmatches1[key] += 1
            else:
                nonmatches1[key] = 1
                
    matches2 = {}
    nonmatches2 = {}
    for i in range(len(matrix2)):
        row = matrix2[i]
        if row in matrix1:
            key = ''.join(str(e) for e in row)
            if key in matches2:
                matches2[key] += 1
            else:
                matches2[key] = 1
        else:
            key = ''.join(str(e) for e in row)
            if key in nonmatches2:
                nonmatches2[key] += 1
            else:
                nonmatches2[key] = 1
                
    matches = [matches1, nonmatches1, matches2, nonmatches2]
    
    for key in matches1:
        #lengths of matches1 and matches2 should be the same
        print()
        print("Matrix 1 (Wine Rating: 5): " + key + " Count: " + str(matches1[key]))
        print("Matrix 2 (Wine Rating: 6): " + key + " Count: " + str(matches2[key]))
        print("Total: " + str(matches1[key] + matches2[key]))
        count1 = 0
        count0 = 0
        for letter in key:
            if letter == "1":
                count1 += 1
            else:
                count0 += 1
        print("1 Vote Count: " + str(count1))
        print("0 Vote Count: " + str(count0))
    
    print()
    print("Non-Matches in Matrix 1: ")
    for key in nonmatches1:
        #lengths of matches1 and matches2 should be the same
        print()
        print("Matrix 1 (Wine Rating: 5): " + key + " Count: " + str(nonmatches1[key]))
        count1 = 0
        count0 = 0
        for letter in key:
            if letter == "1":
                count1 += 1
            else:
                count0 += 1
        print("1 Vote Count: " + str(count1))
        print("0 Vote Count: " + str(count0))
        
    print()
    print("Non-Matches in Matrix 2:")
    for key in nonmatches2:
        #lengths of matches1 and matches2 should be the same
        print()
        print("Matrix 2 (Wine Rating: 6): " + key + " Count: " + str(nonmatches2[key]))
        count1 = 0
        count0 = 0
        for letter in key:
            if letter == "1":
                count1 += 1
            else:
                count0 += 1
        print("1 Vote Count: " + str(count1))
        print("0 Vote Count: " + str(count0))
    

print()
print("Matching Predictions:")
predictions = match_predictions(matrix_5, matrix_6)

Length matrix_5:
495

Length matrix_6:
459

Matching Predictions:

Matrix 1 (Wine Rating: 5): 001100011000100 Count: 262
Matrix 2 (Wine Rating: 6): 001100011000100 Count: 220
Total: 482
1 Vote Count: 5
0 Vote Count: 10

Matrix 1 (Wine Rating: 5): 001100001000100 Count: 60
Matrix 2 (Wine Rating: 6): 001100001000100 Count: 46
Total: 106
1 Vote Count: 4
0 Vote Count: 11

Matrix 1 (Wine Rating: 5): 001110011100111 Count: 19
Matrix 2 (Wine Rating: 6): 001110011100111 Count: 46
Total: 65
1 Vote Count: 9
0 Vote Count: 6

Matrix 1 (Wine Rating: 5): 001110011100100 Count: 121
Matrix 2 (Wine Rating: 6): 001110011100100 Count: 118
Total: 239
1 Vote Count: 7
0 Vote Count: 8

Matrix 1 (Wine Rating: 5): 001110001100100 Count: 27
Matrix 2 (Wine Rating: 6): 001110001100100 Count: 23
Total: 50
1 Vote Count: 6
0 Vote Count: 9

Matrix 1 (Wine Rating: 5): 001100010000100 Count: 2
Matrix 2 (Wine Rating: 6): 001100010000100 Count: 1
Total: 3
1 Vote Count: 4
0 Vote Count: 11

Matrix 1 (Wine Rating: 5): 001100000000100 Count: 1
Matrix 2 (Wine Rating: 6): 001100000000100 Count: 1
Total: 2
1 Vote Count: 3
0 Vote Count: 12

Matrix 1 (Wine Rating: 5): 001110001101100 Count: 2
Matrix 2 (Wine Rating: 6): 001110001101100 Count: 3
Total: 5
1 Vote Count: 7
0 Vote Count: 8

Non-Matches in Matrix 1:

Matrix 1 (Wine Rating: 5): 001110010100100 Count: 1
1 Vote Count: 6
0 Vote Count: 9

Non-Matches in Matrix 2:

Matrix 2 (Wine Rating: 6): 001100001001100 Count: 1
1 Vote Count: 5
0 Vote Count: 10

# Reflection

Alright, this did not go as planned. There was only 1 sequence of votes that belonged to each rating exclusively. Upon realizing this I tried to identify trends in the placement and counts of 1 and 0 in each classification that would help clearly identify 5 or 6. This proved very difficult because of the roughly 50/50 ratio of vote counts between ratings of 5 and 6.

For example, when I ran this the first time the row with predictions "001100011000100" had a count of 262 in wine ratings of 5 and 220 in wine ratings of 6. Since we know that a wine rating of 6 is more likely to be incorrectly classified, we can start to identify that predictions of this count in context of a wine rating of 6 are actually high quality. This high amount of matches is bad when it comes to distinguishing high and low quality. 

What was interesting is I found there is only one row that distinctly does not match in each classifier. 

This will be very difficult to solve because the classification of 5 vs 6 are nearly identical and have very similar quantities of those classifications. Like I said before 262 5's and 220 6's have the classification '001100011000100' meaning that there is about a 50% chance the random forest gets this right. 

I can think of two ways to solve this but it would have to happen at the wrangling period. One, I could one hot encode another column (which would create 3) to include in the random forest and see if that extra value differentiates enough between quality ratings of 5 and 6. Two, adding stricter boundaries when one hot encoding the already existing columns, specifically when they are binned. Hopefully in one of the columns there is a numerical difference where for example "6's always have a lower acidity" but there is a possibility that such a limit does not exist. 

By looking at the matrix of predictions I have verified that the issue with classification of quality is distinguishing between ratings of 5 and 6 because they overwhelmingly get the same votes. This means that when conducting a study on this data in terms of quality that 6 should be a cutoff for high quality.