<h1>
<center>
Final Project: Wine Quality
</center>
</h1>

# Read in spreadsheet

In [1]:
import pandas as pd
import os

from week2 import *
from week3 import *
from week4 import *
from week5 import *
from week6 import *
from week7 import *

url = 'https://docs.google.com/spreadsheets/d/1SF9DGShsQOv0IyxjMIHzQUZbjFwXzY3eC8SSofl53xI/export?format=csv'
wine_table = pd.read_csv(url)

In [2]:
#I am setting the option to see all the columns of our table as we build it.
pd.set_option('display.max_columns', None)

In [3]:
# Check to make sure wine_table is looking correct
wine_table.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [4]:
#get a count of empties in each column
wine_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
#there should be no nulls so we are going to make some in two columns
#in a previous assignment (Loan Data, LoanAmount) the amount of nulls we had was 22/614
print(len(wine_table['density']))
#our length should be 1599 so I am going to use this ratio to randomly assign NaN values

1599

In [6]:
import random

#assign nulls
def assign_nulls(table, target):
    """
    table => our input table (wine_table in this case)
    target => our target column
    """
    #length of column
    column_size = len(table[target])
    
    #using a ratio of 5 to 20 percent nulls, may add customization to this later
    ratio = float(random.randint(5, 20)/100)
    int_ratio = int(ratio * column_size)
    
    #gather random indices
    indices = random.sample(range(column_size), int_ratio)
    #sourced from https://stackoverflow.com/questions/6482889/get-random-sample-from-list-while-maintaining-ordering-of-items
    
    #assign nulls to randomly selected indices
    for i in indices:
        table.at[i, target] = "NaN"
    
    return table

In [7]:
wine_table['prev_density'] = wine_table['density']
wine_table = assign_nulls(wine_table, 'density')
wine_table['no_density'] = wine_table.apply(lambda row: 1 if pd.isnull(row.density) else 0, axis=1)

In [8]:
#should have some nulls now
#get a count of empties in each column
wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                 239
pH                        0
sulphates                 0
alcohol                   0
quality                   0
prev_density              0
no_density                0
dtype: int64

In [9]:
#We need two columns to have nulls in them so lets use the alcohol column as well
wine_table['quality'] = wine_table.apply(lambda row: float(row.quality), axis=1)
wine_table['prev_quality'] = wine_table['quality']
wine_table = assign_nulls(wine_table, 'quality')
wine_table['no_quality'] = wine_table.apply(lambda row: 1 if pd.isnull(row.quality) else 0, axis=1)

wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                 239
pH                        0
sulphates                 0
alcohol                   0
quality                 255
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

In [10]:
wine_table.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,prev_density,no_density,prev_quality,no_quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,NaN,3.51,0.56,9.4,5.0,0.9978,1,5.0,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0,0.9968,0,5.0,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,NaN,3.26,0.65,9.8,5.0,0.9970,1,5.0,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0,0.9980,0,6.0,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,0.9978,0,5.0,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5.0,0.9978,0,5.0,0
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5.0,0.9964,0,5.0,0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7.0,0.9946,0,7.0,0
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7.0,0.9968,0,7.0,0
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5.0,0.9978,0,5.0,0

# Oh No!!!! 

It looks like someone put some random NaN values in our dataset resulting in some density values missing and more importantly, wine quality! 

In order to solve our problem we are going to have to predict the quality of the other wines based on what data we have left. A perfect job for K Means!

# K Means: Predicting Missing Values

I have the final centroids for wine_table so now I am going to use it to predict the NaN values that I set in 'Density' and 'Quality'. Now I have to compute centroids for all the rows that have a 'Density' and all the rows that have 'Quality'. Add the respective values to each centroid and compute the average of the final, that way I have an average of each centroid. 

These isnull() checks may have counts that vary from the isnull() checks above because some rows may have NaN for density and quality and are removed subsequently.

In [11]:
#Going to need a sample table with all the rows with Density
density_table = wine_table[wine_table.density.notnull()]

#to check for nulls
density_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                   0
pH                        0
sulphates                 0
alcohol                   0
quality                 215
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

In [12]:
#all of the features are numeric so I can use them
#we have left out quality because it may have NaN's so it would mess up predictions
d_features = [
 'fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'pH',
 'sulphates',
 'alcohol',
 'density'
]

In [13]:
#create centroids for each table, going to use a k of 10 (centroids) for now
k = 15

In [14]:
#use k_means() to move the rest of the rows into their respective clusters
d_final_centroids = k_means(density_table, d_features, k, {'n':100, 'threshold':0.0})

starting 1
starting 2
starting 3
starting 4
starting 5
starting 6
starting 7
starting 8
starting 9
starting 10
starting 11
starting 12
starting 13
starting 14
starting 15
starting 16
starting 17
starting 18
starting 19
starting 20
starting 21
starting 22
starting 23
starting 24
starting 25
starting 26
starting 27
starting 28
starting 29
starting 30
starting 31
starting 32
starting 33
starting 34
starting 35
starting 36
starting 37
starting 38
starting 39
starting 40
starting 41
starting 42
starting 43
starting 44
starting 45
starting 46
starting 47
starting 48
done

In [15]:
#the last element is the density mean at that centroid
print("Density Final Centroids")
for i in range(k):
    print(d_final_centroids[i]['centroid'])

Density Final Centroids
[8.298717948717949, 0.491602564102564, 0.26564102564102565, 2.615384615384616, 0.08920512820512823, 30.064102564102566, 67.52564102564102, 3.3373076923076925, 0.6569230769230767, 10.35128205128205, 0.9969844871794871]
[8.231884057971012, 0.49442028985507247, 0.2637681159420291, 2.2340579710144914, 0.0766086956521739, 30.507246376811594, 51.65217391304348, 3.3565217391304345, 0.7188405797101449, 10.656521739130437, 0.9964771014492759]
[8.110476190476192, 0.49314285714285694, 0.2352380952380952, 2.523809523809524, 0.07759047619047618, 21.79047619047619, 42.857142857142854, 3.33942857142857, 0.6708571428571428, 10.675714285714289, 0.9963507619047618]
[7.9, 0.3, 0.68, 8.3, 0.05, 37.5, 283.5, 3.01, 0.51, 12.3, 0.99316]
[8.310169491525427, 0.5254661016949151, 0.25610169491525414, 2.2593220338983047, 0.07887288135593222, 11.26271186440678, 22.406779661016948, 3.3196610169491536, 0.6692372881355935, 10.683898305084739, 0.9962586440677962]
[9.136666666666661, 0.4954333333333335, 0.3419333333333332, 2.609333333333334, 0.08964000000000003, 6.453333333333333, 17.946666666666665, 3.263466666666665, 0.6747333333333331, 10.573666666666664, 0.9971102666666667]
[8.082022471910115, 0.5601685393258427, 0.2753932584269663, 2.3752808988764045, 0.10975280898876401, 16.348314606741575, 62.21348314606742, 3.294044943820225, 0.6755056179775281, 9.97734082396629, 0.9970658426966295]
[8.273076923076925, 0.49961538461538474, 0.2888461538461538, 4.576923076923077, 0.10096153846153845, 45.19230769230769, 85.11538461538461, 3.3019230769230767, 0.6488461538461537, 10.27115384615385, 0.9973223076923078]
[7.905714285714287, 0.540642857142857, 0.2814285714285715, 2.940714285714286, 0.08339999999999999, 22.714285714285715, 108.07142857142857, 3.266428571428572, 0.6597142857142859, 10.145238095242858, 0.9966624285714278]
[8.606015037593986, 0.5362781954887217, 0.29120300751879674, 2.569924812030075, 0.09369172932330831, 11.447368421052632, 43.40601503759399, 3.3089473684210513, 0.6375939849624062, 10.15112781954887, 0.9974015789473685]
[9.047422680412375, 0.5029381443298967, 0.3042268041237113, 2.283505154639176, 0.08237113402061856, 7.329896907216495, 28.4020618556701, 3.2611340206185573, 0.661443298969072, 10.203780068659793, 0.9974984536082477]
[8.161363636363635, 0.5840909090909091, 0.3020454545454546, 3.084090909090909, 0.09072727272727273, 32.80681818181818, 137.52272727272728, 3.233636363636364, 0.738636363636364, 9.738636363636362, 0.9972827272727276]
[7.645783132530119, 0.5943373493975906, 0.2444578313253011, 2.6421686746987953, 0.08795180722891564, 18.650602409638555, 87.144578313253, 3.3444578313253017, 0.6372289156626504, 10.073895582409637, 0.9968271084337352]
[7.785401459854021, 0.5389781021897811, 0.18941605839416056, 2.2076642335766428, 0.0820802919708029, 15.10948905109489, 31.21167883211679, 3.368686131386864, 0.636204379562044, 10.56934306569343, 0.9962332116788316]
[8.32893081761006, 0.5300943396226413, 0.27163522012578634, 2.4836477987421377, 0.08348427672955977, 4.70440251572327, 11.30817610062893, 3.3210062893081758, 0.6144025157232705, 10.873899371069186, 0.9961411320754721]

In [16]:
print("Density Clusters")
for i in range(k):
    print(len(d_final_centroids[i]['cluster']))

Density Clusters
78
69
105
2
118
150
89
26
70
133
97
44
83
137
159

In [17]:
import math
#Now we just need to get the rows with NaN's a nearest centroid and assign the average (mean) to that row
def predict_nans(centroids, table, target, features, k):
    for i in range(len(table)):
        row = table.iloc[i]
        if math.isnan(row[target]):
            vrow = row_to_vect(row, features) #vrow import from class library
            (index, dist) = closest_centroid(centroids, vrow, k)
            table.at[i, target] = centroids[index]['centroid'][-1] #last element was the mean
            centroids[index]['cluster'].append(vrow)
    return [table, centroids]

In [18]:
density_predicted = predict_nans(d_final_centroids, wine_table, 'density', d_features, k)
wine_table = density_predicted[0]
d_final_centroids = density_predicted[1]

wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                   0
pH                        0
sulphates                 0
alcohol                   0
quality                 255
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

# Now for Quality Predictions

Phew! We got some pretty good predictions for our density back, but that's only half our problem. Let's use our newfound predictions to help us determine the quality of these wines!

In [19]:
#Going to need a sample table with all the rows that have values for Quality
quality_table = wine_table[wine_table.quality.notnull()]

#to check for nulls
quality_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
prev_density            0
no_density              0
prev_quality            0
no_quality              0
dtype: int64

In [20]:
#inserting density into our features because we want to account for th
q_features = [
 'fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'pH',
 'sulphates',
 'alcohol',
 'density',
 'quality'
]

# Quality K Means

I am running k_means() again because the last centroids do not have the predictions accounted for in their clusters. Running this again will further refine our centroids location in relation to all the rows/points and will give us a more accurate wine quality rating.

In [21]:
#use k_means() to move the rest of the rows into their respective clusters
#my first one took 49 times
q_final_centroids = k_means(quality_table, q_features, k, {'n':100, 'threshold':0.0})

starting 1
starting 2
starting 3
starting 4
starting 5
starting 6
starting 7
starting 8
starting 9
starting 10
starting 11
starting 12
starting 13
starting 14
starting 15
starting 16
starting 17
starting 18
starting 19
starting 20
starting 21
starting 22
starting 23
starting 24
starting 25
starting 26
starting 27
starting 28
starting 29
starting 30
starting 31
starting 32
starting 33
starting 34
starting 35
starting 36
starting 37
starting 38
starting 39
starting 40
starting 41
starting 42
starting 43
starting 44
starting 45
starting 46
starting 47
starting 48
starting 49
starting 50
starting 51
starting 52
starting 53
starting 54
starting 55
starting 56
starting 57
starting 58
starting 59
starting 60
starting 61
starting 62
starting 63
starting 64
starting 65
starting 66
starting 67
starting 68
starting 69
starting 70
starting 71
starting 72
starting 73
starting 74
starting 75
starting 76
starting 77
starting 78
starting 79
starting 80
starting 81
starting 82
done

In [22]:
#the last element is the quality mean at that centroid
print("Quality Final Centroids")
for i in range(k):
    print(q_final_centroids[i]['centroid'])

Quality Final Centroids
[9.029166666666667, 0.5113020833333332, 0.3203124999999998, 2.669791666666667, 0.09458333333333334, 12.572916666666666, 45.572916666666664, 3.286875, 0.6730208333333335, 10.418750000000001, 0.9975147382478634, 5.65625]
[8.53888888888889, 0.4790277777777777, 0.3036111111111112, 2.709722222222223, 0.08876388888888892, 31.27777777777778, 68.97222222222223, 3.313055555555555, 0.669722222222222, 10.365277777777775, 0.997122984330484, 5.638888888888889]
[8.122727272727271, 0.528090909090909, 0.23036363636363627, 2.3127272727272734, 0.09029090909090912, 14.127272727272727, 36.61818181818182, 3.3554545454545437, 0.6342727272727275, 10.324545454545449, 0.9969380163170163, 5.7]
[8.243076923076922, 0.5313461538461538, 0.2672307692307693, 2.373076923076924, 0.08183846153846153, 4.6, 10.807692307692308, 3.323230769230771, 0.6069230769230767, 10.946538461538461, 0.9960137564102557, 5.707692307692308]
[8.151428571428573, 0.5865000000000001, 0.3138571428571429, 2.481428571428571, 0.11092857142857142, 15.642857142857142, 70.45714285714286, 3.3105714285714285, 0.6804285714285713, 9.984047619042858, 0.9971129761904761, 5.3]
[7.411111111111114, 0.5361111111111111, 0.17888888888888882, 2.1060606060606064, 0.07645454545454551, 15.262626262626263, 26.92929292929293, 3.3652525252525285, 0.6435353535353537, 10.836868686868678, 0.9957136195286193, 5.797979797979798]
[8.866233766233767, 0.5431168831168831, 0.2611688311688311, 2.3168831168831177, 0.08012987012987013, 8.03896103896104, 30.38961038961039, 3.2824675324675336, 0.6340259740259739, 10.13982683974026, 0.9974140892440894, 5.584415584415584]
[7.956097560975607, 0.5312195121951219, 0.2873170731707317, 4.317073170731708, 0.09707317073170732, 40.90243902439025, 94.46341463414635, 3.2678048780487807, 0.6102439024390244, 10.103658536585364, 0.9970984365228267, 5.390243902439025]
[7.810476190476196, 0.5964761904761904, 0.25076190476190474, 2.807619047619048, 0.08854285714285712, 18.895238095238096, 96.21904761904761, 3.3217142857142865, 0.6334285714285713, 9.990793650828572, 0.9968289694749696, 5.3428571428571425]
[8.13050847457627, 0.5690677966101697, 0.30983050847457644, 3.2491525423728818, 0.08822033898305086, 31.10169491525424, 136.3728813559322, 3.241864406779661, 0.6974576271186446, 9.77457627118644, 0.997156090830074, 5.101694915254237]
[8.899342105263155, 0.5174342105263158, 0.3080263157894738, 2.5953947368421058, 0.09111842105263163, 6.368421052631579, 16.55263157894737, 3.279210526315789, 0.6584210526315788, 10.629934210526311, 0.997033435391363, 5.8881578947368425]
[7.985000000000001, 0.48975, 0.24012499999999998, 2.4168750000000006, 0.07575, 24.925, 42.825, 3.327000000000001, 0.6807500000000002, 10.795625, 0.9961351041666667, 5.9625]
[9.031297709923667, 0.48648854961832033, 0.3141984732824429, 2.420992366412214, 0.0854503816793893, 8.732824427480915, 22.51145038167939, 3.2741221374045804, 0.688167938931298, 10.367557251908394, 0.9972025406146015, 5.740458015267175]
[7.673684210526315, 0.5217105263157895, 0.20789473684210524, 2.0539473684210527, 0.07357894736842106, 34.73684210526316, 55.18421052631579, 3.387105263157895, 0.6847368421052633, 10.342105263157892, 0.9965191025641027, 5.684210526315789]
[8.245238095238099, 0.5141071428571428, 0.2753571428571429, 2.3547619047619044, 0.09984523809523806, 18.61904761904762, 55.57142857142857, 3.318095238095239, 0.7096428571428569, 10.276190476190475, 0.9970868482905986, 5.619047619047619]

In [23]:
print("Quality Clusters")
for i in range(k):
    print(len(q_final_centroids[i]['cluster']))

Quality Clusters
96
72
110
130
70
99
77
41
105
59
152
80
131
38
84

In [24]:
quality_predicted = predict_nans(q_final_centroids, wine_table, 'quality', q_features, k)
wine_table = quality_predicted[0]
q_final_centroids = quality_predicted[1]

wine_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
prev_density            0
no_density              0
prev_quality            0
no_quality              0
dtype: int64

# Results
Here are the results from using k_means() as a way to predict values. 

prev_density and prev_alcohol columns are the actual values from the dataset that were preserved to compare with.
density and alcohol columns contain the predicted NaN values based on the other values in their column. 
no_density and no_alcohol show which rows were set to NaN, if 1 then NaN, if 0 the value was left alone.

In [25]:
#wine_table.head(20)
view_results = wine_table[['prev_density', 'density', 'no_density', 'prev_quality', 'quality', 'no_quality']]
view_results.head(30)

    prev_density   density  no_density  prev_quality  quality  no_quality
0         0.9978  0.996984           1           5.0  5.00000           0
1         0.9968  0.996800           0           5.0  5.00000           0
2         0.9970  0.996984           1           5.0  5.00000           0
3         0.9980  0.998000           0           6.0  6.00000           0
4         0.9978  0.997800           0           5.0  5.00000           0
5         0.9978  0.997800           0           5.0  5.00000           0
6         0.9964  0.996400           0           5.0  5.00000           0
7         0.9946  0.994600           0           7.0  7.00000           0
8         0.9968  0.996800           0           7.0  7.00000           0
9         0.9978  0.997800           0           5.0  5.00000           0
10        0.9959  0.995900           0           5.0  5.65625           1
11        0.9978  0.997800           0           5.0  5.00000           0
12        0.9943  0.994300           0           5.0  5.00000           0
13        0.9974  0.997400           0           5.0  5.00000           0
14        0.9986  0.998600           0           5.0  5.00000           0
15        0.9986  0.998600           0           5.0  5.00000           0
16        0.9969  0.996900           0           7.0  5.65625           1
17        0.9968  0.996800           0           5.0  5.00000           0
18        0.9974  0.997400           0           4.0  4.00000           0
19        0.9969  0.996900           0           6.0  6.00000           0
20        0.9968  0.996984           1           6.0  6.00000           0
21        0.9982  0.998200           0           5.0  5.00000           0
22        0.9966  0.996600           0           5.0  5.00000           0
23        0.9968  0.996800           0           5.0  5.00000           0
24        0.9968  0.996800           0           6.0  6.00000           0
25        0.9955  0.995500           0           5.0  5.00000           0
26        0.9962  0.996200           0           5.0  5.00000           0
27        0.9966  0.996600           0           5.0  5.00000           0
28        0.9972  0.997200           0           5.0  5.65625           1
29        0.9964  0.996400           0           6.0  6.00000           0

# Reflection

The density predictions came out really nicely but the quality predictions seem to stay around the same centroid. I think this is because the values were originally integers and that makes the euclidean distances and mean between the rows/points very clear cut. Hence why we are getting ratings around 5 for values that should be near 7. The algorithm works well for density because there is more variability in the numeric value. I ran k_means() twice because I noticed the centroids clusters were altered a bit after adding back in the predicted data from density. I was hoping the centroids would move closer to the means of the quality values. When I increase K this does improve a little bit but not to any significant degree. I was thinking about turning the quality into a binary target column but the cut-off would be very harsh considering most of the recommended wines could be considered outliers. All in all, it does underestimate values of wine so when one is rated high, it is rated very high! If you asked my program to give you recomendations of what to drink, it would only give you the best!

# Binary Target Column

Figured I would implement it just to demonstrate the cut off of quality. The numbers for density are so close that a binary target wouldn't really matter.

In [26]:
sigma_quality =  view_results['quality'].std() # calculate std
mean_quality =   view_results['quality'].mean()# calculate mean
low_quality = mean_quality - sigma_quality
high_quality = mean_quality + sigma_quality
print((low_quality, high_quality))

(4.907335932966297, 6.38765312269349)

In [27]:
view_results['quality_rating'] = view_results.apply(lambda row: "High" if row.quality >= high_quality else "Low", axis=1)
view_results['quality_rating_binary'] = view_results.apply(lambda row: 1 if row.quality >= high_quality else 0, axis=1)

/Users/alecsavvy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/alecsavvy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [28]:
view_results.head(20)

,prev_density,density,no_density,prev_quality,quality,no_quality,quality_rating,quality_rating_binary
0,0.9978,0.996984,1,5.0,5.00000,0,Low,0
1,0.9968,0.996800,0,5.0,5.00000,0,Low,0
2,0.9970,0.996984,1,5.0,5.00000,0,Low,0
3,0.9980,0.998000,0,6.0,6.00000,0,Low,0
4,0.9978,0.997800,0,5.0,5.00000,0,Low,0
5,0.9978,0.997800,0,5.0,5.00000,0,Low,0
6,0.9964,0.996400,0,5.0,5.00000,0,Low,0
7,0.9946,0.994600,0,7.0,7.00000,0,High,1
8,0.9968,0.996800,0,7.0,7.00000,0,High,1
9,0.9978,0.997800,0,5.0,5.00000,0,Low,0
10,0.9959,0.995900,0,5.0,5.65625,1,Low,0
11,0.9978,0.997800,0,5.0,5.00000,0,Low,0
12,0.9943,0.994300,0,5.0,5.00000,0,Low,0
13,0.9974,0.997400,0,5.0,5.00000,0,Low,0
14,0.9986,0.998600,0,5.0,5.00000,0,Low,0
15,0.9986,0.998600,0,5.0,5.00000,0,Low,0
16,0.9969,0.996900,0,7.0,5.65625,1,Low,0
17,0.9968,0.996800,0,5.0,5.00000,0,Low,0
18,0.9974,0.997400,0,4.0,4.00000,0,Low,0
19,0.9969,0.996900,0,6.0,6.00000,0,Low,0

In [29]:
view_results['quality_rating'].value_counts()

Low     1416
High     183
Name: quality_rating, dtype: int64