<h1>
<center>
Final Project: Wine Quality
</center>
</h1>

# Read in spreadsheet

In [3]:
import pandas as pd
import os

url = 'https://docs.google.com/spreadsheets/d/1SF9DGShsQOv0IyxjMIHzQUZbjFwXzY3eC8SSofl53xI/export?format=csv'
wine_table = pd.read_csv(url)

In [4]:
#I am setting the option to see all the columns of our table as we build it.
pd.set_option('display.max_columns', None)

In [5]:
# Check to make sure wine_table is looking correct
wine_table.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [6]:
#get a count of empties in each column
wine_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [7]:
#there should be no nulls so we are going to make some in two columns
#in a previous assignment (Loan Data, LoanAmount) the amount of nulls we had was 22/614
print(len(wine_table['density']))
#our length should be 1599 so I am going to use this ratio to randomly assign NaN values

1599

In [8]:
import random

#assign nulls
def assign_nulls(table, target):
    """
    table => our input table (wine_table in this case)
    target => our target column
    """
    #length of column
    column_size = len(table[target])
    
    #using a ratio of 5 to 20 percent nulls, may add customization to this later
    ratio = float(random.randint(5, 20)/100)
    int_ratio = int(ratio * column_size)
    
    #gather random indices
    indices = random.sample(range(column_size), int_ratio)
    #sourced from https://stackoverflow.com/questions/6482889/get-random-sample-from-list-while-maintaining-ordering-of-items
    
    #assign nulls to randomly selected indices
    for i in indices:
        table.at[i, target] = "NaN"
    
    return table

In [9]:
wine_table['prev_density'] = wine_table['density']
wine_table = assign_nulls(wine_table, 'density')
wine_table['no_density'] = wine_table.apply(lambda row: 1 if pd.isnull(row.density) else 0, axis=1)

In [10]:
#should have some nulls now
#get a count of empties in each column
wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                 223
pH                        0
sulphates                 0
alcohol                   0
quality                   0
prev_density              0
no_density                0
dtype: int64

In [11]:
#We need two columns to have nulls in them so lets use the alcohol column as well
wine_table['quality'] = wine_table.apply(lambda row: float(row.quality), axis=1)
wine_table['prev_quality'] = wine_table['quality']
wine_table = assign_nulls(wine_table, 'quality')
wine_table['no_quality'] = wine_table.apply(lambda row: 1 if pd.isnull(row.quality) else 0, axis=1)

wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                 223
pH                        0
sulphates                 0
alcohol                   0
quality                 175
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

In [12]:
wine_table.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,prev_density,no_density,prev_quality,no_quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,NaN,0.9978,0,5.0,1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,NaN,3.20,0.68,9.8,5.0,0.9968,1,5.0,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0,0.9970,0,5.0,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0,0.9980,0,6.0,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0,0.9978,0,5.0,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,NaN,3.51,0.56,9.4,5.0,0.9978,1,5.0,0
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5.0,0.9964,0,5.0,0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,NaN,3.39,0.47,10.0,7.0,0.9946,1,7.0,0
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7.0,0.9968,0,7.0,0
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5.0,0.9978,0,5.0,0

# Oh No!!!! 

It looks like someone put some random NaN values in our dataset resulting in some density values missing and more importantly, wine quality! 

In order to solve our problem we are going to have to predict the quality of the other wines based on what data we have left. A perfect job for K Means!

In [13]:
home_path =  os.path.expanduser('~')
os.chdir(home_path + '/CIS_399/datascience_1/')
!git pull

Already up-to-date.

In [14]:
import sys
sys.path.append(home_path + '/CIS_399/datascience_1')
from week7 import *
%who function

accuracy	 assign_nulls	 build_pred	 build_tree_iter	 caser	 closest_centroid	 compute_mean	 compute_prediction	 compute_training
euclidean_distance	 f1	 find_best_splitter	 forest_builder	 generate_table	 gig	 gini	 informedness	 initialize_centroids
k_fold	 k_means	 phase_1	 phase_2	 predictor_case	 probabilities	 row_to_vect	 seeder	 tree_predictor
vote_taker

# K Means: Predicting Missing Values

I have the final centroids for wine_table so now I am going to use it to predict the NaN values that I set in 'Density' and 'Quality'. Now I have to compute centroids for all the rows that have a 'Density' and all the rows that have 'Quality'. Add the respective values to each centroid and compute the average of the final, that way I have an average of each centroid. 

These isnull() checks may have counts that vary from the isnull() checks above because some rows may have NaN for density and quality and are removed subsequently.

In [15]:
#Going to need a sample table with all the rows with Density
density_table = wine_table[wine_table.density.notnull()]

#to check for nulls
density_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                   0
pH                        0
sulphates                 0
alcohol                   0
quality                 160
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

In [16]:
#all of the features are numeric so I can use them
#we have left out quality because it may have NaN's so it would mess up predictions
d_features = [
 'fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'pH',
 'sulphates',
 'alcohol',
 'density'
]

In [17]:
#create centroids for each table, going to use a k of 10 (centroids) for now
k = 15

In [18]:
#use k_means() to move the rest of the rows into their respective clusters
d_final_centroids = k_means(density_table, d_features, k, {'n':100, 'threshold':0.0})

starting 1
starting 2
starting 3
starting 4
starting 5
starting 6
starting 7
starting 8
starting 9
starting 10
starting 11
starting 12
starting 13
starting 14
starting 15
starting 16
starting 17
starting 18
starting 19
starting 20
starting 21
starting 22
starting 23
starting 24
starting 25
starting 26
starting 27
starting 28
starting 29
starting 30
starting 31
starting 32
starting 33
starting 34
starting 35
starting 36
starting 37
starting 38
starting 39
starting 40
starting 41
starting 42
starting 43
starting 44
starting 45
starting 46
done

In [19]:
#the last element is the density mean at that centroid
print("Density Final Centroids")
for i in range(k):
    print(d_final_centroids[i]['centroid'])

Density Final Centroids
[8.038636363636364, 0.48238636363636345, 0.24602272727272734, 2.2596590909090897, 0.0783636363636364, 31.102272727272727, 60.13636363636363, 3.3669318181818184, 0.673409090909091, 10.549999999999999, 0.9966011363636366]
[8.627536231884056, 0.5150362318840579, 0.28623188405797084, 2.5115942028985514, 0.09313043478260871, 13.88768115942029, 41.77536231884058, 3.3194927536231877, 0.654855072463768, 10.371739130434776, 0.9971998550724634]
[8.531249999999998, 0.49822916666666667, 0.30916666666666665, 4.098958333333334, 0.09789583333333336, 38.541666666666664, 79.53125, 3.29875, 0.6766666666666666, 10.211458333333335, 0.9974560416666663]
[8.546153846153844, 0.5519871794871797, 0.24935897435897436, 2.294230769230769, 0.08657692307692309, 8.794871794871796, 34.35897435897436, 3.3116666666666674, 0.589871794871795, 10.083333333333332, 0.9972553846153847]
[7.704081632653063, 0.5963265306122448, 0.23969387755102037, 2.8306122448979583, 0.08337755102040814, 19.540816326530614, 93.01020408163265, 3.3453061224489797, 0.625204081632653, 10.197278911602043, 0.996715714285714]
[9.259154929577457, 0.5088732394366198, 0.3401408450704226, 2.45105633802817, 0.09437323943661971, 5.753521126760563, 16.380281690140844, 3.251901408450703, 0.6645070422535209, 10.446830985915488, 0.9972888028169019]
[8.344444444444445, 0.595925925925926, 0.3444444444444445, 3.5148148148148146, 0.08911111111111113, 34.592592592592595, 156.14814814814815, 3.21, 0.6137037037037038, 9.90740740740741, 0.9968925925925924]
[7.932307692307693, 0.5386153846153845, 0.307846153846154, 3.1953846153846155, 0.09007692307692305, 28.753846153846155, 118.1076923076923, 3.238307692307693, 0.7183076923076928, 9.867692307692309, 0.9971487692307687]
[8.162096774193554, 0.5224193548387096, 0.2653225806451614, 2.4233870967741957, 0.07974193548387094, 4.709677419354839, 10.725806451612904, 3.3346774193548407, 0.601048387096774, 11.054032258064517, 0.9958067741935478]
[9.28260869565218, 0.48047826086956513, 0.34339130434782605, 2.3930434782608696, 0.08466956521739126, 7.8, 24.721739130434784, 3.2653913043478253, 0.7009565217391305, 10.342753623130436, 0.9975799130434784]
[8.172727272727276, 0.5641558441558442, 0.3064935064935065, 2.4870129870129865, 0.10740259740259737, 16.493506493506494, 69.88311688311688, 3.294155844155844, 0.6663636363636362, 9.910173160168831, 0.9970607792207791]
[7.697368421052632, 0.5108552631578946, 0.2092105263157895, 2.4638157894736845, 0.07571052631578945, 26.789473684210527, 44.328947368421055, 3.356184210526316, 0.6748684210526319, 10.791447368421052, 0.9957431578947367]
[7.593023255813958, 0.5314341085271319, 0.19186046511627897, 2.11860465116279, 0.08097674418604649, 15.790697674418604, 29.170542635658915, 3.366589147286823, 0.656279069767442, 10.750775193798448, 0.9957530232558134]
[8.289473684210526, 0.5286315789473682, 0.2612631578947368, 2.5010526315789474, 0.09072631578947364, 16.768421052631577, 53.55789473684211, 3.3066315789473704, 0.6866315789473681, 10.266315789473683, 0.9970868421052631]
[7.844736842105266, 0.5497368421052631, 0.21947368421052632, 2.3065789473684206, 0.0787894736842105, 10.56578947368421, 19.657894736842106, 3.341710526315787, 0.631447368421053, 10.727631578947365, 0.9959099999999996]

In [20]:
print("Density Clusters")
for i in range(k):
    print(len(d_final_centroids[i]['cluster']))

Density Clusters
88
138
48
78
98
142
27
65
124
115
77
76
129
95
76

In [21]:
import math
#Now we just need to get the rows with NaN's a nearest centroid and assign the average (mean) to that row
def predict_nans(centroids, table, target, features, k):
    for i in range(len(table)):
        row = table.iloc[i]
        if math.isnan(row[target]):
            vrow = row_to_vect(row, features) #vrow import from class library
            (index, dist) = closest_centroid(centroids, vrow, k)
            table.at[i, target] = centroids[index]['centroid'][-1] #last element was the mean
            centroids[index]['cluster'].append(vrow)
    return [table, centroids]

In [22]:
density_predicted = predict_nans(d_final_centroids, wine_table, 'density', d_features, k)
wine_table = density_predicted[0]
d_final_centroids = density_predicted[1]

wine_table.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                   0
pH                        0
sulphates                 0
alcohol                   0
quality                 175
prev_density              0
no_density                0
prev_quality              0
no_quality                0
dtype: int64

# Now for Quality Predictions

Phew! We got some pretty good predictions for our density back, but that's only half our problem. Let's use our newfound predictions to help us determine the quality of these wines!

In [23]:
#Going to need a sample table with all the rows that have values for Quality
quality_table = wine_table[wine_table.quality.notnull()]

#to check for nulls
quality_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
prev_density            0
no_density              0
prev_quality            0
no_quality              0
dtype: int64

In [24]:
#inserting density into our features because we want to account for th
q_features = [
 'fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'pH',
 'sulphates',
 'alcohol',
 'density',
 'quality'
]

# Quality K Means

I am running k_means() again because the last centroids do not have the predictions accounted for in their clusters. Running this again will further refine our centroids location in relation to all the rows/points and will give us a more accurate wine quality rating.

In [25]:
#use k_means() to move the rest of the rows into their respective clusters
#my first one took 49 times
q_final_centroids = k_means(quality_table, q_features, k, {'n':100, 'threshold':0.0})

starting 1
starting 2
starting 3
starting 4
starting 5
starting 6
starting 7
starting 8
starting 9
starting 10
starting 11
starting 12
starting 13
starting 14
starting 15
starting 16
starting 17
starting 18
starting 19
starting 20
starting 21
starting 22
starting 23
starting 24
starting 25
starting 26
starting 27
starting 28
starting 29
starting 30
starting 31
starting 32
starting 33
starting 34
starting 35
starting 36
starting 37
starting 38
starting 39
starting 40
starting 41
starting 42
starting 43
starting 44
starting 45
starting 46
starting 47
starting 48
done

In [26]:
#the last element is the quality mean at that centroid
print("Quality Final Centroids")
for i in range(k):
    print(q_final_centroids[i]['centroid'])

Quality Final Centroids
[8.910191082802541, 0.5163057324840766, 0.3097452229299364, 2.5484076433121023, 0.09049681528662423, 6.2993630573248405, 16.598726114649683, 3.274076433121018, 0.6538216560509552, 10.53343949044586, 0.997021411407065, 5.764331210191083]
[8.245112781954887, 0.5307894736842105, 0.2636842105263159, 2.4056390977443622, 0.07997744360902255, 4.56390977443609, 10.81203007518797, 3.3206015037593994, 0.6036090225563907, 10.935714285714287, 0.9959797368421053, 5.661654135338346]
[8.175675675675675, 0.5618918918918919, 0.3097297297297298, 2.4945945945945946, 0.11291891891891889, 15.95945945945946, 69.8108108108108, 3.292837837837838, 0.6787837837837837, 9.963288288283783, 0.9970202733415232, 5.324324324324325]
[8.692391304347826, 0.5404347826086956, 0.3059782608695651, 2.509782608695653, 0.09944565217391309, 10.467391304347826, 42.20652173913044, 3.3041304347826084, 0.6472826086956522, 10.170652173913039, 0.9974272727272728, 5.467391304347826]
[8.138053097345134, 0.5020796460176988, 0.23769911504424773, 2.3194690265486737, 0.08323008849557523, 18.4070796460177, 38.283185840707965, 3.3442477876106196, 0.6611504424778761, 10.688495575221234, 0.9963725201126307, 5.867256637168142]
[7.935820895522386, 0.5183582089552239, 0.31746268656716425, 3.2947761194029845, 0.0905671641791045, 29.388059701492537, 119.50746268656717, 3.2340298507462686, 0.7240298507462689, 9.843283582089555, 0.9970702849389409, 5.074626865671642]
[7.966666666666667, 0.49050000000000005, 0.288, 4.356666666666668, 0.08723333333333332, 40.96666666666667, 85.35, 3.314, 0.6266666666666666, 10.415000000000001, 0.9965927045454547, 5.8]
[8.320987654320989, 0.5002469135802469, 0.26864197530864203, 2.438888888888889, 0.0875555555555556, 31.54320987654321, 65.34567901234568, 3.342222222222221, 0.6549382716049382, 10.296296296296294, 0.9969327328843992, 5.530864197530864]
[7.766037735849061, 0.6061320754716982, 0.2277358490566037, 2.6330188679245277, 0.08467924528301883, 19.70754716981132, 92.5, 3.3432075471698117, 0.6278301886792451, 10.176729559811317, 0.9968064622641508, 5.4245283018867925]
[8.4, 0.5222330097087378, 0.26407766990291254, 2.5407766990291263, 0.09343689320388347, 16.78640776699029, 53.786407766990294, 3.2979611650485454, 0.6901941747572816, 10.198058252427188, 0.9971085789938217, 5.572815533980583]
[8.332, 0.5960000000000001, 0.3644, 3.6159999999999997, 0.09080000000000002, 33.54, 158.8, 3.2084, 0.6279999999999999, 10.020000000000003, 0.9970261363636365, 5.32]
[7.7378947368421045, 0.5203684210526315, 0.2176842105263158, 2.399473684210525, 0.07554736842105261, 28.768421052631577, 47.97894736842105, 3.3652631578947365, 0.6862105263157895, 10.624736842105264, 0.9961024138755984, 5.778947368421052]
[8.99869281045752, 0.48611111111111094, 0.3200000000000001, 2.4418300653594773, 0.08171895424836598, 9.019607843137255, 22.34640522875817, 3.2758169934640513, 0.6868627450980394, 10.50228758169934, 0.996860484254308, 5.790849673202614]
[8.858241758241764, 0.5362087912087912, 0.2618681318681319, 2.324725274725275, 0.07956043956043954, 8.582417582417582, 30.35164835164835, 3.2940659340659346, 0.6418681318681319, 10.179120879120877, 0.9973865734265731, 5.65934065934066]
[7.388461538461542, 0.5476923076923077, 0.16855769230769224, 2.1552884615384613, 0.07720192307692311, 15.163461538461538, 27.942307692307693, 3.389038461538464, 0.6469230769230769, 10.90432692307692, 0.9957175043706286, 5.836538461538462]

In [27]:
print("Quality Clusters")
for i in range(k):
    print(len(q_final_centroids[i]['cluster']))

Quality Clusters
157
133
74
92
113
67
30
81
106
103
25
95
153
91
104

In [28]:
quality_predicted = predict_nans(q_final_centroids, wine_table, 'quality', q_features, k)
wine_table = quality_predicted[0]
q_final_centroids = quality_predicted[1]

wine_table.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
prev_density            0
no_density              0
prev_quality            0
no_quality              0
dtype: int64

# Results
Here are the results from using k_means() as a way to predict values. 

prev_density and prev_alcohol columns are the actual values from the dataset that were preserved to compare with.
density and alcohol columns contain the predicted NaN values based on the other values in their column. 
no_density and no_alcohol show which rows were set to NaN, if 1 then NaN, if 0 the value was left alone.

In [29]:
#wine_table.head(20)
view_results = wine_table[['prev_density', 'density', 'no_density', 'prev_quality', 'quality', 'no_quality']]
view_results.head(30)

    prev_density   density  no_density  prev_quality   quality  no_quality
0         0.9978  0.997800           0           5.0  5.764331           1
1         0.9968  0.996601           1           5.0  5.000000           0
2         0.9970  0.997000           0           5.0  5.000000           0
3         0.9980  0.998000           0           6.0  6.000000           0
4         0.9978  0.997800           0           5.0  5.000000           0
5         0.9978  0.996601           1           5.0  5.000000           0
6         0.9964  0.996400           0           5.0  5.000000           0
7         0.9946  0.996601           1           7.0  7.000000           0
8         0.9968  0.996800           0           7.0  7.000000           0
9         0.9978  0.997800           0           5.0  5.000000           0
10        0.9959  0.995900           0           5.0  5.000000           0
11        0.9978  0.997800           0           5.0  5.764331           1
12        0.9943  0.994300           0           5.0  5.000000           0
13        0.9974  0.996601           1           5.0  5.000000           0
14        0.9986  0.998600           0           5.0  5.000000           0
15        0.9986  0.998600           0           5.0  5.000000           0
16        0.9969  0.996900           0           7.0  7.000000           0
17        0.9968  0.996800           0           5.0  5.000000           0
18        0.9974  0.997400           0           4.0  4.000000           0
19        0.9969  0.996900           0           6.0  6.000000           0
20        0.9968  0.996800           0           6.0  6.000000           0
21        0.9982  0.998200           0           5.0  5.000000           0
22        0.9966  0.996600           0           5.0  5.000000           0
23        0.9968  0.996800           0           5.0  5.000000           0
24        0.9968  0.996800           0           6.0  6.000000           0
25        0.9955  0.995500           0           5.0  5.000000           0
26        0.9962  0.996200           0           5.0  5.000000           0
27        0.9966  0.996601           1           5.0  5.764331           1
28        0.9972  0.997200           0           5.0  5.000000           0
29        0.9964  0.996400           0           6.0  6.000000           0

# Reflection

The density predictions came out really nicely but the quality predictions seem to stay around the same centroid. I think this is because the values were originally integers and that makes the euclidean distances and mean between the rows/points very clear cut. Hence why we are getting ratings around 5 for values that should be near 7. The algorithm works well for density because there is more variability in the numeric value. I ran k_means() twice because I noticed the centroids clusters were altered a bit after adding back in the predicted data from density. I was hoping the centroids would move closer to the means of the quality values. When I increase K this does improve a little bit but not to any significant degree. I was thinking about turning the quality into a binary target column but the cut-off would be very harsh considering most of the recommended wines could be considered outliers. All in all, it does underestimate values of wine so when one is rated high, it is rated very high! If you asked my program to give you recomendations of what to drink, it would only give you the best!

# Binary Target Column

Figured I would implement it just to demonstrate the cut off of quality. The numbers for density are so close that a binary target wouldn't really matter.

In [33]:
sigma_quality =  view_results['quality'].std() # calculate std
mean_quality =   view_results['quality'].mean()# calculate mean
low_quality = mean_quality - sigma_quality
high_quality = mean_quality + sigma_quality
print((low_quality, high_quality))

(4.887857963279329, 6.403896835699319)

In [40]:
view_results['quality_rating'] = view_results.apply(lambda row: "High" if row.quality >= high_quality else "Low", axis=1)
view_results['quality_rating_binary'] = view_results.apply(lambda row: 1 if row.quality >= high_quality else 0, axis=1)

/Users/alecsavvy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/alecsavvy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [41]:
view_results.head(20)

,prev_density,density,no_density,prev_quality,quality,no_quality,quality_rating,quality_rating_binary
0,0.9978,0.997800,0,5.0,5.764331,1,Low,0
1,0.9968,0.996601,1,5.0,5.000000,0,Low,0
2,0.9970,0.997000,0,5.0,5.000000,0,Low,0
3,0.9980,0.998000,0,6.0,6.000000,0,Low,0
4,0.9978,0.997800,0,5.0,5.000000,0,Low,0
5,0.9978,0.996601,1,5.0,5.000000,0,Low,0
6,0.9964,0.996400,0,5.0,5.000000,0,Low,0
7,0.9946,0.996601,1,7.0,7.000000,0,High,1
8,0.9968,0.996800,0,7.0,7.000000,0,High,1
9,0.9978,0.997800,0,5.0,5.000000,0,Low,0
10,0.9959,0.995900,0,5.0,5.000000,0,Low,0
11,0.9978,0.997800,0,5.0,5.764331,1,Low,0
12,0.9943,0.994300,0,5.0,5.000000,0,Low,0
13,0.9974,0.996601,1,5.0,5.000000,0,Low,0
14,0.9986,0.998600,0,5.0,5.000000,0,Low,0
15,0.9986,0.998600,0,5.0,5.000000,0,Low,0
16,0.9969,0.996900,0,7.0,7.000000,0,High,1
17,0.9968,0.996800,0,5.0,5.000000,0,Low,0
18,0.9974,0.997400,0,4.0,4.000000,0,Low,0
19,0.9969,0.996900,0,6.0,6.000000,0,Low,0

In [42]:
view_results['quality_rating'].value_counts()

Low     1407
High     192
Name: quality_rating, dtype: int64